# Generated by Django 3.2.5 on 2021-07-19 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0003_auto_20210719_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='numofdays',
            new_name='exp',
        ),
    ]
